name: equinv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ca-certificates
  - cxx-compiler
  - openssl
  - tqdm
  - wandb
  - ipython
  - certifi
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.5.1+cu121
    - numpy==1.26.2
    - pandas==2.2.2
    - scipy==1.11.4
    - networkx
    - matplotlib
    - rdkit
    - lightning==2.4.0
    - torchmetrics==1.4.0
    - openbabel-wheel
    - typing_extensions
